[vars]
mise_en_orbeet_version = "branch/default"
mise_en_orbeet_modules = "go"

[tasks.generate]
description = "Generate all needed source files"
sources = [
  "*.go",
  "cmd/schema-generate/*.go",
  "go.mod",
  "go.sum",
  "test/*.json",
]
outputs = [
  "schema-generate",
  "test/*_gen/generated.go",
]
run = """
CGO_ENABLED=0 go build -o schema-generate ./cmd/schema-generate/ && \
cd test && \
rm -rf *_gen && \
for f in *.json; do \
    name=$(echo $f | sed s/.json//); \
    dir=${name}_gen; \
    mkdir -p "$dir"; \
    args=$(jq '.__test_args__' -r "$f"); \
    if [ "$args" = "null" ]; then args=""; fi; \
    ../schema-generate -p "$name" -o "$dir/generated.go" $args "$f" || true; \
done
"""

[tasks.test]
depends = ["generate"]
description = "Run the tests"
run = """
go test -race ./...
cd test && go test -race ./...
"""

[tasks.clean]
description = "Remove the generator binary and generated test code"
run = """
rm -f schema-generate
rm -rf test/*_gen
"""
